// app/data.ts
export const overallTrackerData = [
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-yellow-600", tooltip: "Warn" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-red-600", tooltip: "Error" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
  { color: "bg-emerald-600", tooltip: "Tracker Info" },
];

export const storageUnitsData = [
  {
    href: "/dashboard",
    id: "A12I",
    location: "Pasar Pondok Labu",
    temperature: "5°C",
    efficiency: 98,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "B24J",
    location: "Kantin UPNVJ",
    temperature: "6°C",
    efficiency: 94,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-yellow-600", tooltip: "Warn" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "C64K",
    location: "Area 51 Pondok Indah Mall",
    temperature: "3°C",
    efficiency: 89,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-red-600", tooltip: "Error" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "D24L",
    location: "Pasar Pondok Labu",
    temperature: "5°C",
    efficiency: 98,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "E31M",
    location: "Pasar Pondok Labu",
    temperature: "5°C",
    efficiency: 98,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "F23N",
    location: "Pasar Pondok Labu",
    temperature: "5°C",
    efficiency: 98,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "G790",
    location: "Pasar Pondok Labu",
    temperature: "5°C",
    efficiency: 98,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
  {
    id: "H21P",
    location: "Pasar Pondok Labu",
    temperature: "5°C",
    efficiency: 98,
    trackerData: [
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
      { color: "bg-emerald-600", tooltip: "Tracker Info" },
    ],
  },
];
